use rugui2::{
    events::{EnvEventStates, Key}, math::Vector, styles::ImageData, Gui
};
use winit::{dpi::PhysicalPosition, event::WindowEvent, keyboard::NamedKey};

pub fn event<Msg: Clone, Img: Clone + ImageData>(winit: &WindowEvent, gui: &mut Gui<Msg, Img>) -> EnvEventStates {
    match winit {
        WindowEvent::DroppedFile(path_buf) => gui.env_event(rugui2::events::EnvEvents::FileDrop {
            path: Some(path_buf.clone()),
            opt: rugui2::events::FileDropOpts::Drop,
        }),
        WindowEvent::HoveredFile(path_buf) => gui.env_event(rugui2::events::EnvEvents::FileDrop {
            path: Some(path_buf.clone()),
            opt: rugui2::events::FileDropOpts::Hover,
        }),
        WindowEvent::HoveredFileCancelled => gui.env_event(rugui2::events::EnvEvents::FileDrop {
            path: None,
            opt: rugui2::events::FileDropOpts::Cancel,
        }),
        WindowEvent::KeyboardInput {
            event,
            is_synthetic: false,
            ..
        } => {
            let press = event.state == winit::event::ElementState::Pressed;
            if press && !gui.selection.locked {
                match event.logical_key {
                    winit::keyboard::Key::Named(winit::keyboard::NamedKey::Tab) => {
                        return gui.env_event(rugui2::events::EnvEvents::Select {
                            opt: rugui2::events::SelectOpts::Next,
                        })
                    }
                    winit::keyboard::Key::Named(winit::keyboard::NamedKey::Enter) => {
                        return gui.env_event(rugui2::events::EnvEvents::Select {
                            opt: rugui2::events::SelectOpts::Confirm,
                        })
                    }
                    _ => (),
                }
                if gui.selection.menu_accessibility {
                    match event.logical_key {
                        winit::keyboard::Key::Named(NamedKey::ArrowDown) => {
                            return gui.env_event(rugui2::events::EnvEvents::Select {
                                opt: rugui2::events::SelectOpts::Next,
                            })
                        }
                        winit::keyboard::Key::Named(NamedKey::ArrowRight) => {
                            return gui.env_event(rugui2::events::EnvEvents::Select {
                                opt: rugui2::events::SelectOpts::Next,
                            })
                        }
                        winit::keyboard::Key::Named(NamedKey::ArrowUp) => {
                            return gui.env_event(rugui2::events::EnvEvents::Select {
                                opt: rugui2::events::SelectOpts::Prev,
                            })
                        }
                        winit::keyboard::Key::Named(NamedKey::ArrowLeft) => {
                            return gui.env_event(rugui2::events::EnvEvents::Select {
                                opt: rugui2::events::SelectOpts::Prev,
                            })
                        }
                        winit::keyboard::Key::Named(NamedKey::Escape) => {
                            return gui.env_event(rugui2::events::EnvEvents::Select {
                                opt: rugui2::events::SelectOpts::NoFocus,
                            })
                        }
                        _ => (),
                    }
                }
            }
            if let Some(txt) = &event.text {
                if gui.selection.current().is_some() {
                    gui.env_event(rugui2::events::EnvEvents::Input {
                        text: txt.to_string(),
                    });
                }
            }
            if let winit::keyboard::Key::Named(key) = &event.logical_key {
                gui.env_event(rugui2::events::EnvEvents::KeyPress {
                    key: winit_2_rugui_key(key),
                    press,
                })
            } else {
                EnvEventStates::Free
            }
        }
        WindowEvent::ModifiersChanged(_) => EnvEventStates::Free,
        WindowEvent::CursorMoved { position, .. } => {
            gui.env_event(rugui2::events::EnvEvents::CursorMove {
                pos: Vector(position.x as _, position.y as _),
            })
        }
        WindowEvent::MouseWheel { delta, .. } => gui.env_event(rugui2::events::EnvEvents::Scroll {
            delta: match delta {
                winit::event::MouseScrollDelta::LineDelta(x, y) => Vector(*x, *y),
                winit::event::MouseScrollDelta::PixelDelta(PhysicalPosition { x, y }) => {
                    Vector(*x as _, *y as _)
                }
            },
        }),
        WindowEvent::MouseInput { state, button, .. } => {
            gui.env_event(rugui2::events::EnvEvents::MouseButton {
                button: match button {
                    winit::event::MouseButton::Left => rugui2::events::MouseButtons::Left,
                    winit::event::MouseButton::Right => rugui2::events::MouseButtons::Right,
                    winit::event::MouseButton::Middle => rugui2::events::MouseButtons::Middle,
                    _ => return EnvEventStates::Free,
                },
                press: match state {
                    winit::event::ElementState::Pressed => true,
                    winit::event::ElementState::Released => false,
                },
            })
        }
        WindowEvent::PinchGesture { .. } => EnvEventStates::Free,
        WindowEvent::PanGesture { .. } => EnvEventStates::Free,
        WindowEvent::DoubleTapGesture { .. } => EnvEventStates::Free,
        WindowEvent::RotationGesture { .. } => EnvEventStates::Free,
        WindowEvent::TouchpadPressure { .. } => EnvEventStates::Free,
        WindowEvent::Touch(_) => EnvEventStates::Free,
        _ => EnvEventStates::Free,
    }
}

fn winit_2_rugui_key(key: &NamedKey) -> Key {
    match key {
        NamedKey::Alt => Key::Alt,
        NamedKey::AltGraph => Key::AltGraph,
        NamedKey::CapsLock => Key::CapsLock,
        NamedKey::Control => Key::Control,
        NamedKey::Fn => Key::Fn,
        NamedKey::FnLock => Key::FnLock,
        NamedKey::NumLock => Key::NumLock,
        NamedKey::ScrollLock => Key::ScrollLock,
        NamedKey::Shift => Key::Shift,
        NamedKey::Symbol => Key::Symbol,
        NamedKey::SymbolLock => Key::SymbolLock,
        NamedKey::Meta => Key::Meta,
        NamedKey::Hyper => Key::Hyper,
        NamedKey::Super => Key::Super,
        NamedKey::Enter => Key::Enter,
        NamedKey::Tab => Key::Tab,
        NamedKey::Space => Key::Space,
        NamedKey::ArrowDown => Key::ArrowDown,
        NamedKey::ArrowLeft => Key::ArrowLeft,
        NamedKey::ArrowRight => Key::ArrowRight,
        NamedKey::ArrowUp => Key::ArrowUp,
        NamedKey::End => Key::End,
        NamedKey::Home => Key::Home,
        NamedKey::PageDown => Key::PageDown,
        NamedKey::PageUp => Key::PageUp,
        NamedKey::Backspace => Key::Backspace,
        NamedKey::Clear => Key::Clear,
        NamedKey::Copy => Key::Copy,
        NamedKey::CrSel => Key::CrSel,
        NamedKey::Cut => Key::Cut,
        NamedKey::Delete => Key::Delete,
        NamedKey::EraseEof => Key::EraseEof,
        NamedKey::ExSel => Key::ExSel,
        NamedKey::Insert => Key::Insert,
        NamedKey::Paste => Key::Paste,
        NamedKey::Redo => Key::Redo,
        NamedKey::Undo => Key::Undo,
        NamedKey::Accept => Key::Accept,
        NamedKey::Again => Key::Again,
        NamedKey::Attn => Key::Attn,
        NamedKey::Cancel => Key::Cancel,
        NamedKey::ContextMenu => Key::ContextMenu,
        NamedKey::Escape => Key::Escape,
        NamedKey::Execute => Key::Execute,
        NamedKey::Find => Key::Find,
        NamedKey::Help => Key::Help,
        NamedKey::Pause => Key::Pause,
        NamedKey::Play => Key::Play,
        NamedKey::Props => Key::Props,
        NamedKey::Select => Key::Select,
        NamedKey::ZoomIn => Key::ZoomIn,
        NamedKey::ZoomOut => Key::ZoomOut,
        NamedKey::BrightnessDown => Key::BrightnessDown,
        NamedKey::BrightnessUp => Key::BrightnessUp,
        NamedKey::Eject => Key::Eject,
        NamedKey::LogOff => Key::LogOff,
        NamedKey::Power => Key::Power,
        NamedKey::PowerOff => Key::PowerOff,
        NamedKey::PrintScreen => Key::PrintScreen,
        NamedKey::Hibernate => Key::Hibernate,
        NamedKey::Standby => Key::Standby,
        NamedKey::WakeUp => Key::WakeUp,
        NamedKey::AllCandidates => Key::AllCandidates,
        NamedKey::Alphanumeric => Key::Alphanumeric,
        NamedKey::CodeInput => Key::CodeInput,
        NamedKey::Compose => Key::Compose,
        NamedKey::Convert => Key::Convert,
        NamedKey::FinalMode => Key::FinalMode,
        NamedKey::GroupFirst => Key::GroupFirst,
        NamedKey::GroupLast => Key::GroupLast,
        NamedKey::GroupNext => Key::GroupNext,
        NamedKey::GroupPrevious => Key::GroupPrevious,
        NamedKey::ModeChange => Key::ModeChange,
        NamedKey::NextCandidate => Key::NextCandidate,
        NamedKey::NonConvert => Key::NonConvert,
        NamedKey::PreviousCandidate => Key::PreviousCandidate,
        NamedKey::Process => Key::Process,
        NamedKey::SingleCandidate => Key::SingleCandidate,
        NamedKey::HangulMode => Key::HangulMode,
        NamedKey::HanjaMode => Key::HanjaMode,
        NamedKey::JunjaMode => Key::JunjaMode,
        NamedKey::Eisu => Key::Eisu,
        NamedKey::Hankaku => Key::Hankaku,
        NamedKey::Hiragana => Key::Hiragana,
        NamedKey::HiraganaKatakana => Key::HiraganaKatakana,
        NamedKey::KanaMode => Key::KanaMode,
        NamedKey::KanjiMode => Key::KanjiMode,
        NamedKey::Katakana => Key::Katakana,
        NamedKey::Romaji => Key::Romaji,
        NamedKey::Zenkaku => Key::Zenkaku,
        NamedKey::ZenkakuHankaku => Key::ZenkakuHankaku,
        NamedKey::Soft1 => Key::Soft1,
        NamedKey::Soft2 => Key::Soft2,
        NamedKey::Soft3 => Key::Soft3,
        NamedKey::Soft4 => Key::Soft4,
        NamedKey::ChannelDown => Key::ChannelDown,
        NamedKey::ChannelUp => Key::ChannelUp,
        NamedKey::Close => Key::Close,
        NamedKey::MailForward => Key::MailForward,
        NamedKey::MailReply => Key::MailReply,
        NamedKey::MailSend => Key::MailSend,
        NamedKey::MediaClose => Key::MediaClose,
        NamedKey::MediaFastForward => Key::MediaFastForward,
        NamedKey::MediaPause => Key::MediaPause,
        NamedKey::MediaPlay => Key::MediaPlay,
        NamedKey::MediaPlayPause => Key::MediaPlayPause,
        NamedKey::MediaRecord => Key::MediaRecord,
        NamedKey::MediaRewind => Key::MediaRewind,
        NamedKey::MediaStop => Key::MediaStop,
        NamedKey::MediaTrackNext => Key::MediaTrackNext,
        NamedKey::MediaTrackPrevious => Key::MediaTrackPrevious,
        NamedKey::New => Key::New,
        NamedKey::Open => Key::Open,
        NamedKey::Print => Key::Print,
        NamedKey::Save => Key::Save,
        NamedKey::SpellCheck => Key::SpellCheck,
        NamedKey::Key11 => Key::Key11,
        NamedKey::Key12 => Key::Key12,
        NamedKey::AudioBalanceLeft => Key::AudioBalanceLeft,
        NamedKey::AudioBalanceRight => Key::AudioBalanceRight,
        NamedKey::AudioBassBoostDown => Key::AudioBassBoostDown,
        NamedKey::AudioBassBoostToggle => Key::AudioBassBoostToggle,
        NamedKey::AudioBassBoostUp => Key::AudioBassBoostUp,
        NamedKey::AudioFaderFront => Key::AudioFaderFront,
        NamedKey::AudioFaderRear => Key::AudioFaderRear,
        NamedKey::AudioSurroundModeNext => Key::AudioSurroundModeNext,
        NamedKey::AudioTrebleDown => Key::AudioTrebleDown,
        NamedKey::AudioTrebleUp => Key::AudioTrebleUp,
        NamedKey::AudioVolumeDown => Key::AudioVolumeDown,
        NamedKey::AudioVolumeUp => Key::AudioVolumeUp,
        NamedKey::AudioVolumeMute => Key::AudioVolumeMute,
        NamedKey::MicrophoneToggle => Key::MicrophoneToggle,
        NamedKey::MicrophoneVolumeDown => Key::MicrophoneVolumeDown,
        NamedKey::MicrophoneVolumeUp => Key::MicrophoneVolumeUp,
        NamedKey::MicrophoneVolumeMute => Key::MicrophoneVolumeMute,
        NamedKey::SpeechCorrectionList => Key::SpeechCorrectionList,
        NamedKey::SpeechInputToggle => Key::SpeechInputToggle,
        NamedKey::LaunchApplication1 => Key::LaunchApplication1,
        NamedKey::LaunchApplication2 => Key::LaunchApplication2,
        NamedKey::LaunchCalendar => Key::LaunchCalendar,
        NamedKey::LaunchContacts => Key::LaunchContacts,
        NamedKey::LaunchMail => Key::LaunchMail,
        NamedKey::LaunchMediaPlayer => Key::LaunchMediaPlayer,
        NamedKey::LaunchMusicPlayer => Key::LaunchMusicPlayer,
        NamedKey::LaunchPhone => Key::LaunchPhone,
        NamedKey::LaunchScreenSaver => Key::LaunchScreenSaver,
        NamedKey::LaunchSpreadsheet => Key::LaunchSpreadsheet,
        NamedKey::LaunchWebBrowser => Key::LaunchWebBrowser,
        NamedKey::LaunchWebCam => Key::LaunchWebCam,
        NamedKey::LaunchWordProcessor => Key::LaunchWordProcessor,
        NamedKey::BrowserBack => Key::BrowserBack,
        NamedKey::BrowserFavorites => Key::BrowserFavorites,
        NamedKey::BrowserForward => Key::BrowserForward,
        NamedKey::BrowserHome => Key::BrowserHome,
        NamedKey::BrowserRefresh => Key::BrowserRefresh,
        NamedKey::BrowserSearch => Key::BrowserSearch,
        NamedKey::BrowserStop => Key::BrowserStop,
        NamedKey::AppSwitch => Key::AppSwitch,
        NamedKey::Call => Key::Call,
        NamedKey::Camera => Key::Camera,
        NamedKey::CameraFocus => Key::CameraFocus,
        NamedKey::EndCall => Key::EndCall,
        NamedKey::GoBack => Key::GoBack,
        NamedKey::GoHome => Key::GoHome,
        NamedKey::HeadsetHook => Key::HeadsetHook,
        NamedKey::LastNumberRedial => Key::LastNumberRedial,
        NamedKey::Notification => Key::Notification,
        NamedKey::MannerMode => Key::MannerMode,
        NamedKey::VoiceDial => Key::VoiceDial,
        NamedKey::TV => Key::TV,
        NamedKey::TV3DMode => Key::TV3DMode,
        NamedKey::TVAntennaCable => Key::TVAntennaCable,
        NamedKey::TVAudioDescription => Key::TVAudioDescription,
        NamedKey::TVAudioDescriptionMixDown => Key::TVAudioDescriptionMixDown,
        NamedKey::TVAudioDescriptionMixUp => Key::TVAudioDescriptionMixUp,
        NamedKey::TVContentsMenu => Key::TVContentsMenu,
        NamedKey::TVDataService => Key::TVDataService,
        NamedKey::TVInput => Key::TVInput,
        NamedKey::TVInputComponent1 => Key::TVInputComponent1,
        NamedKey::TVInputComponent2 => Key::TVInputComponent2,
        NamedKey::TVInputComposite1 => Key::TVInputComposite1,
        NamedKey::TVInputComposite2 => Key::TVInputComposite2,
        NamedKey::TVInputHDMI1 => Key::TVInputHDMI1,
        NamedKey::TVInputHDMI2 => Key::TVInputHDMI2,
        NamedKey::TVInputHDMI3 => Key::TVInputHDMI3,
        NamedKey::TVInputHDMI4 => Key::TVInputHDMI4,
        NamedKey::TVInputVGA1 => Key::TVInputVGA1,
        NamedKey::TVMediaContext => Key::TVMediaContext,
        NamedKey::TVNetwork => Key::TVNetwork,
        NamedKey::TVNumberEntry => Key::TVNumberEntry,
        NamedKey::TVPower => Key::TVPower,
        NamedKey::TVRadioService => Key::TVRadioService,
        NamedKey::TVSatellite => Key::TVSatellite,
        NamedKey::TVSatelliteBS => Key::TVSatelliteBS,
        NamedKey::TVSatelliteCS => Key::TVSatelliteCS,
        NamedKey::TVSatelliteToggle => Key::TVSatelliteToggle,
        NamedKey::TVTerrestrialAnalog => Key::TVTerrestrialAnalog,
        NamedKey::TVTerrestrialDigital => Key::TVTerrestrialDigital,
        NamedKey::TVTimer => Key::TVTimer,
        NamedKey::AVRInput => Key::AVRInput,
        NamedKey::AVRPower => Key::AVRPower,
        NamedKey::ColorF0Red => Key::ColorF0Red,
        NamedKey::ColorF1Green => Key::ColorF1Green,
        NamedKey::ColorF2Yellow => Key::ColorF2Yellow,
        NamedKey::ColorF3Blue => Key::ColorF3Blue,
        NamedKey::ColorF4Grey => Key::ColorF4Grey,
        NamedKey::ColorF5Brown => Key::ColorF5Brown,
        NamedKey::ClosedCaptionToggle => Key::ClosedCaptionToggle,
        NamedKey::Dimmer => Key::Dimmer,
        NamedKey::DisplaySwap => Key::DisplaySwap,
        NamedKey::DVR => Key::DVR,
        NamedKey::Exit => Key::Exit,
        NamedKey::FavoriteClear0 => Key::FavoriteClear0,
        NamedKey::FavoriteClear1 => Key::FavoriteClear1,
        NamedKey::FavoriteClear2 => Key::FavoriteClear2,
        NamedKey::FavoriteClear3 => Key::FavoriteClear3,
        NamedKey::FavoriteRecall0 => Key::FavoriteRecall0,
        NamedKey::FavoriteRecall1 => Key::FavoriteRecall1,
        NamedKey::FavoriteRecall2 => Key::FavoriteRecall2,
        NamedKey::FavoriteRecall3 => Key::FavoriteRecall3,
        NamedKey::FavoriteStore0 => Key::FavoriteStore0,
        NamedKey::FavoriteStore1 => Key::FavoriteStore1,
        NamedKey::FavoriteStore2 => Key::FavoriteStore2,
        NamedKey::FavoriteStore3 => Key::FavoriteStore3,
        NamedKey::Guide => Key::Guide,
        NamedKey::GuideNextDay => Key::GuideNextDay,
        NamedKey::GuidePreviousDay => Key::GuidePreviousDay,
        NamedKey::Info => Key::Info,
        NamedKey::InstantReplay => Key::InstantReplay,
        NamedKey::Link => Key::Link,
        NamedKey::ListProgram => Key::ListProgram,
        NamedKey::LiveContent => Key::LiveContent,
        NamedKey::Lock => Key::Lock,
        NamedKey::MediaApps => Key::MediaApps,
        NamedKey::MediaAudioTrack => Key::MediaAudioTrack,
        NamedKey::MediaLast => Key::MediaLast,
        NamedKey::MediaSkipBackward => Key::MediaSkipBackward,
        NamedKey::MediaSkipForward => Key::MediaSkipForward,
        NamedKey::MediaStepBackward => Key::MediaStepBackward,
        NamedKey::MediaStepForward => Key::MediaStepForward,
        NamedKey::MediaTopMenu => Key::MediaTopMenu,
        NamedKey::NavigateIn => Key::NavigateIn,
        NamedKey::NavigateNext => Key::NavigateNext,
        NamedKey::NavigateOut => Key::NavigateOut,
        NamedKey::NavigatePrevious => Key::NavigatePrevious,
        NamedKey::NextFavoriteChannel => Key::NextFavoriteChannel,
        NamedKey::NextUserProfile => Key::NextUserProfile,
        NamedKey::OnDemand => Key::OnDemand,
        NamedKey::Pairing => Key::Pairing,
        NamedKey::PinPDown => Key::PinPDown,
        NamedKey::PinPMove => Key::PinPMove,
        NamedKey::PinPToggle => Key::PinPToggle,
        NamedKey::PinPUp => Key::PinPUp,
        NamedKey::PlaySpeedDown => Key::PlaySpeedDown,
        NamedKey::PlaySpeedReset => Key::PlaySpeedReset,
        NamedKey::PlaySpeedUp => Key::PlaySpeedUp,
        NamedKey::RandomToggle => Key::RandomToggle,
        NamedKey::RcLowBattery => Key::RcLowBattery,
        NamedKey::RecordSpeedNext => Key::RecordSpeedNext,
        NamedKey::RfBypass => Key::RfBypass,
        NamedKey::ScanChannelsToggle => Key::ScanChannelsToggle,
        NamedKey::ScreenModeNext => Key::ScreenModeNext,
        NamedKey::Settings => Key::Settings,
        NamedKey::SplitScreenToggle => Key::SplitScreenToggle,
        NamedKey::STBInput => Key::STBInput,
        NamedKey::STBPower => Key::STBPower,
        NamedKey::Subtitle => Key::Subtitle,
        NamedKey::Teletext => Key::Teletext,
        NamedKey::VideoModeNext => Key::VideoModeNext,
        NamedKey::Wink => Key::Wink,
        NamedKey::ZoomToggle => Key::ZoomToggle,
        NamedKey::F1 => Key::F1,
        NamedKey::F2 => Key::F2,
        NamedKey::F3 => Key::F3,
        NamedKey::F4 => Key::F4,
        NamedKey::F5 => Key::F5,
        NamedKey::F6 => Key::F6,
        NamedKey::F7 => Key::F7,
        NamedKey::F8 => Key::F8,
        NamedKey::F9 => Key::F9,
        NamedKey::F10 => Key::F10,
        NamedKey::F11 => Key::F11,
        NamedKey::F12 => Key::F12,
        NamedKey::F13 => Key::F13,
        NamedKey::F14 => Key::F14,
        NamedKey::F15 => Key::F15,
        NamedKey::F16 => Key::F16,
        NamedKey::F17 => Key::F17,
        NamedKey::F18 => Key::F18,
        NamedKey::F19 => Key::F19,
        NamedKey::F20 => Key::F20,
        NamedKey::F21 => Key::F21,
        NamedKey::F22 => Key::F22,
        NamedKey::F23 => Key::F23,
        NamedKey::F24 => Key::F24,
        NamedKey::F25 => Key::F25,
        NamedKey::F26 => Key::F26,
        NamedKey::F27 => Key::F27,
        NamedKey::F28 => Key::F28,
        NamedKey::F29 => Key::F29,
        NamedKey::F30 => Key::F30,
        NamedKey::F31 => Key::F31,
        NamedKey::F32 => Key::F32,
        NamedKey::F33 => Key::F33,
        NamedKey::F34 => Key::F34,
        NamedKey::F35 => Key::F35,
        _ => todo!(),
    }
}
